file1 = open("D:/BEBO/Python_SDET/Python-SDET/PracticeSession_20/example.txt","r")
file2 = open("D:/BEBO/Python_SDET/Python-SDET/PracticeSession_20/destination.txt","r")
content1 = file1.read()
content2 = file2.read()
file3 = open("D:/BEBO/Python_SDET/Python-SDET/PracticeSession_20/merge.txt","w")
file3.write(content1 + content2)
file1.close()
file2.close()
file3.close()